#!/bin/bash

main() {
echo ""
echo "What would you like to do today?"
echo "------------------------------------"
echo " 1: Connect to VPN"
echo " 2: Update Machine"
echo " 3: Web"
echo " 4: Connect to VPN and Update"
echo " 5: Kill Packagekit"
echo " 6: Shutdown"
echo "------------------------------------"
read ans
}

update() {
	sudo apt-get update && sudo apt-get full-upgrade -y
	sleep 2s
	clear
}

vpn() {
	#Insert VPN Service Here
	sleep 2s
	clear
}

packkill() {
	ps -A | grep pack*
	echo "-What is the process ID?-"
	read packkill
	if [[ -n $packkill ]]; then
			sudo kill $packkill
	elif [[ -z $packkill ]]; then
			echo "-I can't help you then-"
			sleep 2s
			clear
	fi
}

shutd() {
	shutdown -P now
}

options() {
	if [[ $ans == 1 ]]; then
		vpn
	elif [[ $ans == 2 ]]; then
		update
	elif [[ $ans == 3 ]]; then
		firefox
	elif [[ $ans == 4 ]]; then
		vpn
		update
	elif [[ -z $ans ]]; then
			echo "-Please enter a vaild number-"
			main
			options
	elif [[ $ans == "no" ]]; then
			echo "-Have a nice day!-"
			sleep 2s
			clear
	elif [[ $ans == 5 ]]; then
			packkill
	elif [[ $ans == 6 ]]; then
			shutd
	elif [[ $ans == 7 ]]; then
			./Firew&
	fi
}

main
options
